const jwt = require('jsonwebtoken');
const Developer = require('../models/Developer');
const AppError = require('../utils/AppError');
const { JWT_SECRET, JWT_EXPIRES_IN } = require('../config/env');

// registerDeveloper — creates a new developer; apiKey generated by pre-save hook
const registerDeveloper = async ({ username, email, password }) => {
  const developer = await Developer.create({ username, email, password });
  // Strip password from the returned object — never expose it
  developer.password = undefined;
  return { developer };
};

// loginDeveloper — validates credentials and returns a signed JWT + developer
const loginDeveloper = async ({ email, password }) => {
  // Explicitly select password and apiKey — both excluded by default
  const developer = await Developer.findOne({ email }).select('+password +apiKey');
  // Same message for missing email or wrong password — prevents user enumeration
  if (!developer) throw new AppError('Invalid email or password', 401);

  const isMatch = await developer.comparePassword(password);
  if (!isMatch) throw new AppError('Invalid email or password', 401);

  const token = jwt.sign({ id: developer._id }, JWT_SECRET, { expiresIn: JWT_EXPIRES_IN });
  // Strip password before returning
  developer.password = undefined;
  return { developer, token };
};

module.exports = { registerDeveloper, loginDeveloper };
